version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb1-data:/data/db
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - my-network

  node-app:
    image: dmitrysmetyukhov/test-node-app 
    container_name: node-app-container
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongodb1-data:
    driver: local
